#!/usr/bin/env bash

docker build \
  -t mtodo/foundation \
  dockerfiles/foundation

./script/_run \
  -e HOME="$(pwd)" \
  mtodo/foundation \
  git config --global user.email "robot@mtodo.github.io"

./script/_run \
  -e HOME="$(pwd)" \
  mtodo/foundation \
  git config --global user.name "mtodo robot"
