#!/usr/bin/env bash

bower() {
  cd bower_components/$1
}

bower_end() {
  cd ../..
}

_run() {
  ../../script/_run -e HOME="$(pwd)" mtodo/foundation "$@"
}

script/bower install

# ajv
bower ajv
  _run npm install
  _run node ./scripts/compile-dots.js
  _run npm run bundle
bower_end
