#!/usr/bin/env bash

JSONARY_PATH=modules/jsonary

_run() {
./script/_run \
  -e HOME="$(pwd)/$JSONARY_PATH" \
  -w "$(pwd)/$JSONARY_PATH" \
  mtodo/foundation \
  "$@"
}

git submodule update --init --recursive
_run npm install
_run node assemble-package.js
cp ./$JSONARY_PATH/node-package/core/jsonary-core.js ./test/support/jsonary.js
